<a href="https://colab.research.google.com/github/uluemre/veribilimi/blob/main/odev3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

benzersiz = list(set(notlar))

en_yuksek = max(notlar)
en_dusuk = min(notlar)

sirali = sorted(benzersiz)

print("Benzersiz:", benzersiz)
print("En yüksek:", en_yuksek)
print("En düşük:", en_dusuk)
print("Sıralı:", sirali)


Benzersiz: [100, 92, 85, 76]
En yüksek: 100
En düşük: 76
Sıralı: [76, 85, 92, 100]


In [10]:
def armstrong_mu(sayi):


SyntaxError: incomplete input (ipython-input-2497723952.py, line 1)

In [3]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

print("Ortak:", A & B)
print("Sadece A:", A - B)
print("Birleşim:", sorted(A | B))


Ortak: {'Python', 'SQL'}
Sadece A: {'R', 'Java'}
Birleşim: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [8]:
import random, statistics

sayilar = [random.randint(1, 100) for _ in range(10)]

print("Sayılar:", sayilar)
print("Ortalama:", statistics.mean(sayilar))
print("Standart Sapma:", statistics.stdev(sayilar))


Sayılar: [45, 51, 16, 19, 47, 33, 26, 38, 9, 3]
Ortalama: 28.7
Standart Sapma: 16.7136005828919


In [19]:
def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    en_sık = max(set(kelimeler), key=kelimeler.count)
    return toplam, en_uzun, en_sık

print(kelime_sayaci("python veri yapay zeka zeka veri bilim yapayzeka veri"))


(9, 'yapayzeka', 'veri')


In [20]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x**2, ciftler))
sirali = sorted(kareler, reverse=True)

print("Çiftler:", ciftler)
print("Kareleri:", kareler)
print("Azalan:", sirali)


Çiftler: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Azalan: [576, 324, 256, 144]


In [21]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
sirali = sorted(kelimeler, key=lambda x: len(x))
print(sirali)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [28]:
def rakam_toplam(metin):



SyntaxError: incomplete input (ipython-input-4152318739.py, line 2)

In [31]:
import numpy as np

dizi = np.random.randint(0, 51, 10)
print("Dizi:", dizi)
print("Ortalama:", np.mean(dizi))
print("Std Sapma:", np.std(dizi))
print("Max:", np.max(dizi))


Dizi: [36  8 32  3  6 11 26 20 32  8]
Ortalama: 18.2
Std Sapma: 11.838918869558993
Max: 36


In [33]:
matris = np.random.rand(5, 5)
print("Matris:\n", matris)

sutun_ort = np.mean(matris, axis=0)
print("Sütun Ort:", sutun_ort)

binary = (matris > 0.5).astype(int)
print("Binary Matris:\n", binary)


Matris:
 [[0.48382631 0.28001322 0.95634952 0.02320761 0.77195354]
 [0.1280788  0.69176303 0.23121205 0.26298149 0.35361737]
 [0.78563447 0.75979734 0.25174878 0.32831215 0.86653048]
 [0.64569556 0.89317443 0.17681715 0.2072335  0.10427285]
 [0.17662761 0.19358609 0.64413643 0.85944622 0.12276236]]
Sütun Ort: [0.44397255 0.56366682 0.45205279 0.33623619 0.44382732]
Binary Matris:
 [[0 0 1 0 1]
 [0 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 0 0]
 [0 0 1 1 0]]


In [52]:
import statistics, random
from collections import Counter

kitaplar = [
    {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
    {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
    {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
    {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
    {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
    {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
    {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

# 1.
def en_cok_satan(kitaplar):
    return max(kitaplar, key=lambda x: x["satis"])

def yazar_satislari(kitaplar):
    sonuc = {}
    for k in kitaplar:
        sonuc[k["yazar"]] = sonuc.get(k["yazar"], 0) + k["satis"]
    return sonuc

print(" En çok satan kitap:", en_cok_satan(kitaplar)["isim"])
print(" Yazar satışları:", yazar_satislari(kitaplar))

# 2.
turler = {k["tur"] for k in kitaplar}
fazla_satanlar = [k["isim"] for k in kitaplar if k["satis"] > 1000]

print(" Türler:", turler)
print(" 1000’den fazla satan kitaplar:", fazla_satanlar)

# 3.
yeni_kitaplar = list(filter(lambda k: k["yil"] > 2020, kitaplar))
artisli_satis = list(map(lambda k: k["satis"]*1.1, kitaplar))
sirali = sorted(kitaplar, key=lambda x: x["satis"], reverse=True)

print(" 2020 sonrası çıkanlar:", [k["isim"] for k in yeni_kitaplar])
print(" %10 artışlı satış listesi:", artisli_satis)
print(" Satışa göre sıralı:", [k["isim"] for k in sirali])

# 4.
ortalama = statistics.mean([k["satis"] for k in kitaplar])
stdsapma = statistics.stdev([k["satis"] for k in kitaplar])

tur_sayilari = Counter([k["tur"] for k in kitaplar])
en_cok_tur = max(tur_sayilari, key=tur_sayilari.get)

print(" Ortalama satış:", round(ortalama, 1))
print(" Standart sapma:", round(stdsapma, 1))
print(" En çok satış yapan tür:", en_cok_tur)

# 5.

train = random.sample(kitaplar, int(len(kitaplar)*0.7))
test = [k for k in kitaplar if k not in train]

train_ortalama = statistics.mean([k["satis"] for k in train])
test_ustunde = [k["isim"] for k in test if k["satis"] > train_ortalama]

print(" Train ortalama satış:", round(train_ortalama, 1))
print(" Test verisinde ortalama üstünde satanlar:", test_ustunde)


 En çok satan kitap: Makine Öğrenmesi
 Yazar satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}
 Türler: {'Akademik', 'Bilim', 'Sosyal', 'Sanat'}
 1000’den fazla satan kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
 2020 sonrası çıkanlar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme', 'Bilgi Toplumu']
 %10 artışlı satış listesi: [1320.0, 1045.0, 770.0000000000001, 1980.0000000000002, 440.00000000000006, 1650.0000000000002, 660.0]
 Satışa göre sıralı: ['Makine Öğrenmesi', 'Matematiksel Modelleme', 'Veri Bilimi 101', 'Python ile Yapay Zeka', 'İstatistik Temelleri', 'Bilgi Toplumu', 'Veri Görselleştirme']
 Ortalama satış: 1021.4
 Standart sapma: 506.5
 En çok satış yapan tür: Bilim
 Train ortalama satış: 1087.5
 Test verisinde ortalama üstünde satanlar: ['Makine Öğrenmesi']
